package com.rm.translateit.db.model

import org.greenrobot.greendao.AbstractDao
import org.greenrobot.greendao.AbstractDaoSession
import org.greenrobot.greendao.database.Database
import org.greenrobot.greendao.identityscope.IdentityScopeType
import org.greenrobot.greendao.internal.DaoConfig

import com.rm.translateit.db.model.Language

import com.rm.translateit.db.model.LanguageDao

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}

 * @see org.greenrobot.greendao.AbstractDaoSession
 */
class DaoSession(db: Database, type: IdentityScopeType, daoConfigMap: Map<Class<out AbstractDao<*, *>>, DaoConfig>) : AbstractDaoSession(db) {

    private val languageDaoConfig: DaoConfig

    val languageDao: LanguageDao

    init {

        languageDaoConfig = daoConfigMap[LanguageDao::class.java]!!.clone()
        languageDaoConfig.initIdentityScope(type)

        languageDao = LanguageDao(languageDaoConfig, this)

        registerDao(Language::class.java, languageDao)
    }

    fun clear() {
        languageDaoConfig.clearIdentityScope()
    }

}
